name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: enter
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGUSER: postgres
      PGPASSWORD: enter
      PGHOST: localhost
      PGDATABASE: postgres
      PGPORT: 5432
      LOGLEVEL: debug

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install npm modules
      run: |
        cd public && npm ci && npm run jshint && npm run bundle

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x

    - name: Test
      run: |
        go test ./... -p 1 -coverprofile=profile.cov

    - uses: shogo82148/actions-goveralls@v1.9.1
      with:
        path-to-profile: profile.cov


    - name: Build docker image
      run: |
        docker build . -t ghcr.io/luanti-hosting/mt-hosting-manager:latest

    - name: Log in to the Container registry
      if: success() && github.ref == 'refs/heads/master'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push docker image
      if: success() && github.ref == 'refs/heads/master'
      run: |
        docker push ghcr.io/luanti-hosting/mt-hosting-manager:latest

    - name: Trigger deployment on hosting.luanti.ch
      if: success() && github.ref == 'refs/heads/master'
      uses: benc-uk/workflow-dispatch@v1.2.4
      with:
        workflow: deploy
        repo: luanti-hosting/hosting.luanti.ch
        ref: refs/heads/main
        token: ${{ secrets.GH_DEPLOY_TOKEN }}
